### ISSUE TITLE
any node.js version for this one?

### ISSUE THREAD

**Issue by ahmadkeren** [JakeAve/bingasaurus#3]
sorry maybe my question is out of topic

**Comment by JakeAve** [comment]
No. I haven't made this in node, but there's a list at the bottom of the readme with some places where I drew inspiration, including some in node.js

**Comment by ahmadkeren** [comment]
i tried this at localhost and work perfectly.. 
but when i deploy at ubuntu server, that said "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200"

any solution?

**Comment by JakeAve** [comment]
I have not seen that error. I don't know if it's related to a fire wall or something on the ubuntu server. If you find out what's wrong with it, can you let me know if it's something that can be fixed in the source code?
